# Generated by Django 5.1.3 on 2024-11-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='companyname',
        ),
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.CharField(default='Not Specified', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='website',
            field=models.CharField(default='Not Specified', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(default='Not Specified', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='profile_pic',
            field=models.ImageField(upload_to='job/img/candidate'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_pic',
            field=models.ImageField(upload_to='job/img/company'),
        ),
    ]
