# Generated by Django 5.1.4 on 2025-01-29 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermaster',
            old_name='is_verifird',
            new_name='is_verified',
        ),
    ]
