# Generated by Django 4.2.16 on 2024-11-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_company_name_company_companyname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='profile_pic',
        ),
    ]
