# Generated by Django 4.2.16 on 2024-11-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_candidate_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo_pic',
        ),
    ]
