# Generated by Django 4.2.16 on 2024-11-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_company_logo_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
    ]
