# Generated by Django 4.2.16 on 2024-11-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='name',
            field=models.CharField(default='company', max_length=200),
            preserve_default=False,
        ),
    ]
