# Generated by Django 4.2.16 on 2024-11-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_jobapplication_candidate_jobapplication_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
